FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app
COPY ./src/ .
COPY ./artifacts/entrypoint.sh .
RUN chmod +x ./entrypoint.sh
RUN dotnet restore ./AD.Api
RUN dotnet build ./AD.Api
RUN dotnet publish ./AD.Api -c release --runtime linux-x64
RUN dotnet tool install --global dotnet-ef
ENV PATH = "$PATH:/root/.dotnet/tools"
EXPOSE 5188/tcp
CMD /bin/bash ./entrypoint.sh   